### ISSUE TITLE
Logic: Seeders Error

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#107]
== 00065-CapabilityLanguage: migrating =======
(node:18241) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: SQLITE_ERROR: table CapabilityLanguage has no column named RoleId
    at Query.formatError (/home/cswertz/forschung/projects/1998_lerndorf/test/server/node_modules/sequelize/lib/dialects/sqlite/query.js:415:16)
    at Query._handleQueryResponse (/home/cswertz/forschung/projects/1998_lerndorf/test/server/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/home/cswertz/forschung/projects/1998_lerndorf/test/server/node_modules/sequelize/lib/dialects/sqlite/query.js:246:27)
    at Statement.errBack (/home/cswertz/forschung/projects/1998_lerndorf/test/server/node_modules/sqlite3/lib/sqlite3.js:14:21)
    at Statement.topLevelDomainCallback (domain.js:137:15)
(node:18241) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18241) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
== 00065-CapabilityLanguage: migrated (0.589s)

**Comment by cswertz** [comment]
Column ID changed. No errors on a fresh install. Seems to be fixed.
