### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#70]
## Check
* [x] Username is not shown on profile page
* [x] Error Message when uploading profile image

## Change Request
* [x] Showing the profile picture in the profile data would be could. Otherwise uploading a new picture is not confirmed (unless someone looks at the title bar wihich is rather unlikely)
* [ ]  ~~All field names like "Birthdate" are on top and under the editing field - but not in the "Password" - line. Field names under the editin field are enough.~~

### Logging
* [x] Button with "Show logged data" is needed
* [x] Button with "Delete log data" (with confirmation) is missing
* [x] Button with "Delete profile" (with conformation and confirmation through link in E-Mail) is missing

**Comment by stylesuxx** [comment]
@cswertz Regarding the labels of the fields: They are inside the textbox until you start editing or they already contain value. The ones beneath the textboxes are the help text (where it is also displayed if there is a validation error) I can remove the labels beneath the boxes if you prefer.

**Comment by cswertz** [comment]
Displaying Profile picture ist not working. Maybe a local problem. Console says:
TypeError: req.files.picture.md5 is not a function
    at ./server/routes/users.js.router.patch (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/.build/server.js:3544:40)
    at Layer.handle [as handle_request] (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/route.js:137:13)
    at /home/cswertz/forschung/projects/1998_lerndorf/data/github/server/.build/server.js:1145:14
    at Layer.handle [as handle_request] (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:281:22
    at param (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:354:14)
    at param (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:410:3)
    at next (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:174:3)
    at router (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:317:13)
    at /home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/node_modules/express/lib/router/index.js:275:10)
    at Promise.all.then.values (/home/cswertz/forschung/projects/1998_lerndorf/data/github/server/.build/server.js:3684:9)
    at <anonymous>

**Comment by cswertz** [comment]
> @cswertz Regarding the labels of the fields: They are inside the textbox until you start editing or they 
already contain value. The ones beneath the textboxes are the help text (where it is also displayed if there is a validation error) I can remove the labels beneath the boxes if you prefer.

Better keep it as is. Thank's for taking a look!

**Comment by stylesuxx** [comment]
Breaking changes have been introduced in the file uploader without bumping the major version number but only the minor.

Still this should not have been a problem since the version is locked in the yarn.lock file. Could you tell me how you installed the dependencies and also what the output of

    node --version

is?

**Comment by cswertz** [comment]
Sorry for tha late reply. Node is 9.11.1. I installed with yarn install.

**Comment by cswertz** [comment]
Profile picture is  not shown in the profile after upload (which is common IMHO). It only pops up after i clicked  "save". Everything else looks good.

**Comment by cswertz** [comment]
BTW: Beeing able to delete a profile picture would be good.

**Comment by cswertz** [comment]
I did a fresh install. Can not find the button for new users. Maybe due to my switch to node 12.6?

I'm still irritated that the picture does not show after I selected it. I tried to change the picture in my google account and it did change straight after uploading (no "save" required). The problem is that I assume something went wrong if I do not see the picture after uploading.

**Comment by stylesuxx** [comment]
The picture is part of another issue. Users can add themselfes, no need for the admin to add them.
